# Generated by Django 3.2.5 on 2021-08-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
